// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function GetCharacters(arg1, arg2) {
  return window['go']['main']['App']['GetCharacters'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetItems(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetItems'](arg1, arg2, arg3);
}

export function GetPassiveSkills(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPassiveSkills'](arg1, arg2, arg3);
}

export function SetPoeSessId(arg1) {
  return window['go']['main']['App']['SetPoeSessId'](arg1);
}
