// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function GetCharacters(arg1:string,arg2:string):Promise<main.StringResult>;

export function GetConfig():Promise<config.Config>;

export function GetItems(arg1:string,arg2:string,arg3:string):Promise<main.StringResult>;

export function GetPassiveSkills(arg1:string,arg2:string,arg3:string):Promise<main.StringResult>;

export function SetPoeSessId(arg1:string):Promise<main.BoolResult>;
